services:
  - type: web
    name: yeka-magic-bags-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    
  - type: web
    name: yeka-magic-bags-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html