services:
  - type: web
    name: yeka-magic-bags-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    
  - type: web
    name: yeka-magic-bags-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars: # <-- Asegúrate de que esta sección esté presente si tienes variables de entorno
      - key: NODE_VERSION
        value: 18
    # --- ¡ESTA ES LA SECCIÓN CLAVE PARA EL REWRITES! ---
    rewrites: # <-- Asegúrate de que 'rewrites' esté al mismo nivel que 'staticPublishPath', 'envVars', etc.
      - source: /*
        destination: /index.html